version: '3'

services:
  nginx:
    container_name: lb
    image: nginx:latest
    depends_on:
      - app1
      - app2
    tty: true
    ports:
      - "80:80"
    volumes:
      - ../nginx/:/etc/nginx/
    networks:
      - backend
  
  app1:
    container_name: app1
    build: ../app/
    tty: true
    networks:
      - backend
  app2:
    container_name: app2
    build: ../app/
    tty: true
    networks:
      - backend

networks:
  backend:

